[loadbalancer]
machineA ansible_host=172.31.8.122 ansible_connection=local

[webservers]
machineB ansible_host=172.31.10.57 machine_label="Machine B"
machineC ansible_host=172.31.0.221 machine_label="Machine C"

[all:vars]
ansible_user=ubuntu
